Завершаем вёрстку адаптивных сеток
htmlacademy-adaptive/322403-pognali-20 pull request #7
Opened 2020-08-24 12:47 UTC by dianova-mila

Почему-то не сработал display flex в .companions-form__group, подскажи пожалуйста почему так?

2020-08-24 14:20 UTC, ILoyso requested changes

2020-08-24 14:20 UTC, ILoyso commented on source/sass/blocks/countries-header.scss
> +}
grid-template-rows: min-content; для десктопа можно не повторять

2020-08-24 14:20 UTC, ILoyso commented on source/sass/blocks/personal-info.scss
> +.personal-info_wrapper {
Элемент? Два подчеркивания тогда

2020-08-24 14:20 UTC, ILoyso commented on source/sass/blocks/personal-info.scss
> +  grid-template-rows: min-content 1fr min-content 1fr;
Давай на мобилке две колонки, все вроде бы помещается в них
http://joxi.ru/52ag5LVhbOgoVr

2020-08-24 14:20 UTC, ILoyso commented on source/sass/blocks/personal-info.scss
> +  }
А вот на таблетке как раз три колонки (и соответственно у вложенных элементов нужно будет переписать свойство grid-column)
http://joxi.ru/L2169ZVTg4zMgA

2020-08-24 14:20 UTC, ILoyso commented on source/sass/blocks/personal-info.scss
> +}
grid-column: 3; для десктопа можно не дублировать

2020-08-24 14:20 UTC, ILoyso commented on source/sass/blocks/personal-info.scss
> +    }
grid-row: 4; можно не дублировать, наследуется с мобилки

2020-08-24 21:08 UTC, dianova-mila commented on source/sass/blocks/personal-info.scss
> +  }
Тут вроде не надо ничего переписывать ибо я так и делала, что планшет три колонки, но потом меня видимо заклинило)

2020-08-25 08:02 UTC, ILoyso approved these changes

2020-08-25 08:02 UTC, merged