Продолжаем вёрстку личного проекта
htmlacademy-adaptive/322403-pognali-20 pull request #8
Opened 2020-08-31 17:29 UTC by dianova-mila

Если сделать размер экрана меньше 320, шапка ломается, это страшно? можно исправить?

2020-08-31 19:20 UTC, ILoyso requested changes
Про какие конкретно ты поломки? Если про то, что справа появляется свободное место - это не из-за хедера, это из-за пока ещё неадаптивного и не стилизованного контента на странице. А если про перенос почты - тут уж никуда не деться. Ну и минимальная возможная высота браузеров это 320, та что все ок

В целом - очень много вложенности тегов. Да, где-то это можно оправдать, но в большинстве случае это усложнение и нужно от этого избавляться. Изменить видимость - можно, какую-нибудь базовую характеристику типа цвета фона/текста/иконки - можно. Все остальное должно быть написано без вложенности в классе самого блока/элемента/модификатора.
Плюс использование одних блоков в стилях других тоже под запретом у нас, исключения есть, но они скорее глобальные какие-то.

2020-08-31 19:20 UTC, ILoyso commented on source/sass/blocks/header.scss
>  }
Не нужно фиксировать ширину на декстопе, переполнение и все такое. Плюс кнопки без боковых паддингов это сразу плохо. Можно сделать так
- заменить тут ширину на максимальную ширину (чтобы при переполнении в какой-то момент кнопка все-таки начинала переноситься)
- у хедера поправить теплейт на grid-template-columns: 200px 2fr 1fr auto;
- у кнопки добавить боковые паддинги

2020-08-31 19:20 UTC, ILoyso commented on source/sass/blocks/header.scss
> +  }
Где-то в процентах пишешь отступы, где-то в пикселях. Давай по большей части в пикселях стараться, иначе в какой-то момент разные единицы измерения становится тяжело друг с другом считать.
На десктопе в микросетках везде пиксели должны быть (или везде проценты, но это сложно и неудобно)

2020-08-31 19:20 UTC, ILoyso commented on source/sass/blocks/header.scss
> +  .contact-link__text {
А зачем нам тут вложенность классов, кстати?
Кажется, что это не сильно нужно и можно модификаторами по месту обойтись, если очень нужно. Плюс такой код развернут по https://up.htmlacademy.ru/adaptive/20/criteries#b13 , так как в файле БЭМ блока должны быть только его элементы и модификаторы

2020-08-31 19:20 UTC, ILoyso commented on source/sass/blocks/header.scss
> +}
Аналогично здесь и везде, где разные блоки намешали. Если что-то где-то меняется, блок сам должен это внутри себя разруливать

2020-08-31 19:20 UTC, ILoyso commented on source/sass/blocks/header.scss
> +  background-color: $basic-blue-dark;
Мне кажется, что ты выбрала более сложный подход. Можно было взять за протой header маленькую версию (свернутую), а с модом показывать дополнительные блоки. Это выглядело бы все проще.

То есть сейчас ты под классом header--closed пишешь кучу дополнительных стилей элементов, хотя должно быть под ним только изменение видимости элементов (и максимум цвет, если нужен)

2020-08-31 19:20 UTC, ILoyso commented on source/sass/blocks/main-nav.scss
> +    }
Это скорее псевдо самого main-nav, потому что он лежит в области его паддинга и удобнее контролировать это в одном месте

2020-09-01 09:51 UTC, dianova-mila commented on source/catalog.html
> +            </svg>
http://joxi.ru/823lY1JcDNkNZA

вот тут меняется цвет иконки и так как я считаю это все один элементом я иконку и в хедер засунула, убрать или норм?

2020-09-01 10:04 UTC, ILoyso commented on source/catalog.html
> +            </svg>
А, если меняется, то везде пихай, для единообразия

2020-09-01 10:19 UTC, dianova-mila commented on source/sass/blocks/header.scss
> +  }
Я не совсем поняла что надо сделать(

2020-09-01 10:29 UTC, dianova-mila commented on source/sass/blocks/main-nav.scss
> +    }
на декстопе, когда шапка из синей становится белой у всех элементов меняются нижние и верхние отступы и чтобы когда размер main-nav изменится не менять положение псевдоэлемента а зацепила его за список чтобы он всегда был рядом с ним, можно я так и оставлю как есть?

2020-09-01 11:46 UTC, ILoyso commented on source/sass/blocks/main-nav.scss
> +    }
Тогда да, пусть висит. Ох уж эти перемещения =/

2020-09-01 11:54 UTC, ILoyso commented on source/sass/blocks/header.scss
> +  }
Оу, ссылка на критерий не прицепилась правильно, вот https://up.htmlacademy.ru/adaptive/20/criteries#b19

Блин, а ещё я поняла, что у нас нет логотипа в svg формате. Значит инлайнить свг не можем, отмена, тогда все верно и логотип в picture должен быть. А перекрашивать его костылями через фон, да =/

2020-09-02 07:23 UTC, ILoyso commented on source/sass/blocks/header.scss
> +}
Посмотри потом, надо бы тоже вынести это отсюда

2020-09-02 07:23 UTC, ILoyso commented on source/sass/blocks/contact.scss
> +  &--mini {
Предлагаю во имя единообразия сделать так же, как в файле с хедером - сложные модификаторы (которые как-то глобально перестраивают стили) писать все-таки ниже и отдельно. Так значительно проще читать)
Если ещё где-то такое есть или будет - лучше тоже как в хедере.
Простые модификаторы оставляем с вложенностью, с ними все ок :)

2020-09-07 06:59 UTC, dianova-mila commented
На плашете у блока направления айтемы какого-то неадекватного размера, хотя должны быть одного размера с картинкой, и у картинки почему-то не работает бордер радиус(

2020-09-07 08:18 UTC, ILoyso commented on source/sass/blocks/promo-list.scss
> +    height: 20px;
Высоту можно не задавать, ну или на планшете переопределять, а то получается, что задана одна, а по факту там другая

2020-09-07 08:18 UTC, ILoyso commented on source/sass/blocks/promo-list.scss
> +    }
Можно было основные значения ширины и марджинов отрицательных написать непосредственно для promo-list__item, а у модификаторов уже только переопределять отличающиеся, было бы чуть поменьше кода

2020-09-07 08:18 UTC, ILoyso commented on source/sass/blocks/button.scss
> +  height: 62px;
Лучше min-height

2020-09-07 08:18 UTC, ILoyso commented on source/sass/blocks/directions.scss
> +  width: 270px;
Если резину делаем, то можно не фиксировать ширину и тянуть весь блок

2020-09-07 08:18 UTC, ILoyso commented on source/sass/blocks/directions-list.scss
>      display: flex;
Нужно на планшете добавить align-items: flex-start и тогда размеры блоков будут нормально паддингами редактироваться

2020-09-07 08:18 UTC, ILoyso commented on source/sass/blocks/directions-list.scss
>  }
Для picture не работаю стили толком, этот тег служит оберткой, а стили нужно писать для img внутри него.
Но в случае с border-radius'ом будет проще задать их самому directions-list__item один раз (все, верхние, нижние и какие там нужны) и добавить overflow-hidden. Вуаля, он режет контент внутри себя :)

2020-09-07 08:49 UTC, dianova-mila commented on source/sass/blocks/directions.scss
> +  width: 270px;
Я на мобилке зафиксировала потому что у меня получается что описание тянется, а картинка не тянется, мне кажется если тянуть картинку она будет странно выглядеть, или есть решение этой проблемы?)

2020-09-07 08:53 UTC, ILoyso commented on source/sass/blocks/directions.scss
> +  width: 270px;
Не, тут если тянуть, то только описание наверное
Ну эт не критично, оставляй как есть, оно в любом случае норм

2020-09-07 08:55 UTC, dianova-mila commented on source/sass/blocks/directions.scss
> +  width: 270px;
А тогда как-то странно смотрится, это же по сути на мое усмотрение) Поэтому там и кнопка зафиксирована в размере на мобилке, так мой внутренний эстет спокоен ахаха)

2020-09-07 13:42 UTC, dianova-mila commented on source/sass/blocks/promo-list.scss
> +    }
По приоритетам получается, что первые значения берутся у  элемента с модификатором + медиа десктоп, потом у этого же элемента + медиа планшет и т.д и потом уже только у элемента без модификатора и получается что я местами переопределяю в самих элементах планшет и по факту почти ничего убрать не могу(

2020-09-09 00:03 UTC, dianova-mila commented
Не совсем представляю как мне оформить этот кружок у level
Значки в иконках транспорта и в кнопки лайка лучше псевдо или вставить в HTML?
В карточках десктоп сломался почему-то, я прям уже не понимаю почему верхний блок такой жирный и всех остальных теснит, и почему если я им задаю min-content они вообще не минимум) Подскажи пожалуйста)

2020-09-09 08:49 UTC, ILoyso requested changes
- Не совсем представляю как мне оформить этот кружок у level
Проще всего svg сделать. Так-то можно было бы на канвасе рисовать, но это все сложнее, так что свг

- Значки в иконках транспорта и в кнопки лайка лучше псевдо или вставить в HTML?
Лучше псевдо

- В карточках десктоп сломался почему-то, я прям уже не понимаю почему верхний блок такой жирный и всех остальных теснит, и почему если я им задаю min-content они вообще не минимум) 
https://developer.mozilla.org/ru/docs/Web/CSS/grid-template-columns - тут про min и max-content
Чтобы работало как ты хочешь, нужно задать `grid-template-rows: max-content min-content min-content;`

2020-09-09 08:49 UTC, ILoyso commented on source/sass/blocks/footer.scss
> +    padding-bottom: 0;
Лучше оставить нижний паддинг не убирать марджины у вложенных элементов. И центровать черерз align-items все, что внутри

2020-09-09 08:49 UTC, ILoyso commented on source/sass/blocks/footer-copyright.scss
> +  }
Просто бордером можно было

2020-09-09 18:24 UTC, ILoyso approved these changes

2020-09-09 18:24 UTC, merged