Продолжаем вёрстку личного проекта
htmlacademy-adaptive/322403-pognali-20 pull request #9
Opened 2020-09-10 13:31 UTC by dianova-mila

index.html

2020-09-10 14:46 UTC, ILoyso requested changes

2020-09-10 14:46 UTC, ILoyso commented on source/sass/blocks/contact.scss
> +    padding-top: 37px;
Вроде ж и без этого норм :D

2020-09-10 14:46 UTC, ILoyso commented on source/sass/blocks/map.scss
> +  margin-bottom: -120px;
Мы все секции друг под друга пихали по одному принципу - верхним отрицательным марджином. Лучше футер так же двигать, а здесь нижний отрицательный убрать

и класс - масло масленое :)

2020-09-10 14:46 UTC, ILoyso commented on source/sass/blocks/level.scss
>  .level__level {
Тоже класс не очень

2020-09-10 14:46 UTC, ILoyso commented on source/sass/blocks/map-text.scss
> +  }
Паддинги кнопка не только сверху и слева нужны :) 
http://joxi.ru/YmEzK6vTJ81KR2

2020-09-10 14:46 UTC, ILoyso commented on source/sass/blocks/map-text.scss
>  .map-text {
Оч странно сделан блок на десктопе, много внутренних отступов намешано, хотя казалось бы - паддинги самого желтого блока, флексом отцентровать относительно друг друга и иконку спозиционировать тоже по центру
http://joxi.ru/LmG9advUJ7EaKA

2020-09-10 14:46 UTC, ILoyso commented on source/index.html
> +    <button class="business-rates__button">Закрыть окно</button>
http://joxi.ru/zANzdOvT6eGp6A
Там если присмотреться, то торчит белый цвет. В таких случаях лучше задавать скругление только для модалки + overlow: hidden, а внутри ничего не скруглять. Модалка сама обрежет в итоге

2020-09-12 20:22 UTC, dianova-mila commented
В companions-form__item текст почему-то не встает как надо по пп(
Как сделать срединку у .filter-level__numbers?
В .countries-filter__item на десктопе тоже почему то не получается выровнять буквы нормально, как так? И еще там нижние отступы у элементов countries-filter__list на макете какие-то странные, как вообще добиться чтобы было по пп?

2020-09-13 11:34 UTC, ILoyso requested changes
> В companions-form__item текст почему-то не встает как надо по пп(

Потому что центровать элементы в строчке нужно не паддингами элементов внутри, а паддингами строки плюс align-items: center. Если убрать почти все паддинги внутри и центровать именно от строки начинать, то более-менее выправляется. А на мелочи меньше 5px смещения можно забить
http://joxi.ru/YmEzK6vTJ8nMb2

> Как сделать срединку у .filter-level__numbers?

Например, вертикальная линия - бордер обычный, пусть она будет без разрыва. А потом псевдоэлементом сверху положить блок горизонтальный, где градиентом с резким переходом задан цвет белый-серый-белый.

> В .countries-filter__item на десктопе тоже почему то не получается выровнять буквы нормально, как так?

http://joxi.ru/Dr8RdxVtzwVMX2
http://joxi.ru/YmEzK6vTJ8nBb2
И пофиг на небольшое расхождение правого столбика, остальные ок и ладно. Ну или делать 4 столбик чуть меньше, но это маразим уже. 

> И еще там нижние отступы у элементов countries-filter__list на макете какие-то странные, как вообще добиться чтобы было по пп?

А что касается отступа перед предпоследней строкой - там косяк в дизайне прям ( http://joxi.ru/V2VbD8jCKb18G2 ), но мы с этим особо сделать ничего не можем, так что добавь для буквы М там модификатор и костыль в виде какого-нибудь нижнего паддинга, чтобы компенсировать эту фигню

2020-09-14 10:47 UTC, merged